version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: always

  backend:
    build:
      context: backend/.
      dockerfile: docker/Dockerfile
    container_name: backend
    environment:
      - "NODE_ENV=production"
      - "MONGO_URL=mongodb://mongo:27017"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    restart: always

  frontend:
    build:
      context: frontend-angularjs/.
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - 80:8080
    restart: always

volumes:
  mongo:
  redis:
